# -*- coding: utf-8 -*-
"""NLP-Text-Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vCCB6W-WlSNuGUBuXN4XFNi9CUeubsAs
"""

# Import basic libraries
import pandas as pd
import numpy as np

# Upload dataset files
from google.colab import files
uploaded = files.upload()

"""Load and View Dataset
👉 What this step does:
Read CSV files
Check data structure
Understand columns
"""

train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

train_df.head()

"""Rename Columns"""

train_df.columns = ['Class', 'Title', 'Description']
test_df.columns = ['Class', 'Title', 'Description']

"""check dataset info"""

# Check dataset shape
print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

# Check column names
print(train_df.columns)

train_df.columns = ['Class', 'Title', 'Description']
test_df.columns = ['Class', 'Title', 'Description']

"""Text Preprocessing
👉 What this step does:
Combine Title + Description
Clean text (lowercase, remove symbols)
Remove stopwords
Prepare final text for ML
"""

train_df['text'] = train_df['Title'] + " " + train_df['Description']
test_df['text'] = test_df['Title'] + " " + test_df['Description']

train_df = train_df[['Class', 'text']]
test_df = test_df[['Class', 'text']]

train_df.head()

# Install nltk
!pip install nltk

import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    words = text.split()  # tokenization

    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]

    return " ".join(words)

# Apply preprocessing
train_df['text'] = train_df['text'].apply(clean_text)
test_df['text'] = test_df['text'].apply(clean_text)

train_df.head()

"""TF-IDF Vectorization"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X_train = tfidf.fit_transform(train_df['text']).toarray()
X_test = tfidf.transform(test_df['text']).toarray()

y_train = train_df['Class']
y_test = test_df['Class']

print(X_train.shape)
lemmatizer = WordNetLemmatizer()

"""Train Model (Naive Bayes)"""

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

"""Prediction"""

y_pred = model.predict(X_test)

"""Evaluation"""

from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

"""CountVectorizer"""

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000)

X_train_cv = cv.fit_transform(train_df['text']).toarray()
X_test_cv = cv.transform(test_df['text']).toarray()

model_cv = MultinomialNB()
model_cv.fit(X_train_cv, y_train)

y_pred_cv = model_cv.predict(X_test_cv)

print("CountVectorizer Accuracy:", accuracy_score(y_test, y_pred_cv))

"""Confusion Matrix"""

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Create confusion matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:\n", cm)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()