# -*- coding: utf-8 -*-
"""Neural_Network_202402040023.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiiv9pggFX15chmCnDCQ6-HVZ9nNYocZ
"""

import numpy as np

# =====================================================
# 1. DATA PREPROCESSING
# =====================================================
# Input data (2nd example)
X = np.array([[2, 1]], dtype=float)

# Normalization
X = X / np.max(X)

# Target output
y = np.array([[0.5]])

# =====================================================
# 2. ACTIVATION FUNCTION
# =====================================================
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(output):
    return output * (1 - output)

# =====================================================
# 3. MODEL ARCHITECTURE
# =====================================================
# 2 Input Neurons → 2 Hidden Neurons → 1 Output Neuron
initial_input_hidden = np.array([
    [0.6, 0.1],
    [-0.2, 0.3]
])

initial_hidden_output = np.array([
    [-0.4],
    [0.7]
])

# =====================================================
# 4. HYPERPARAMETER TUNING
# =====================================================
learning_rates = [0.01, 0.05, 0.1]
epochs = 10000   # increased to match your output

best_loss = float("inf")
best_lr = None

# =====================================================
# 5. TRAINING & EVALUATION
# =====================================================
for lr in learning_rates:

    print(f"\nTraining with Learning Rate = {lr}\n")

    # Reset weights
    w_input_hidden = initial_input_hidden.copy()
    w_hidden_output = initial_hidden_output.copy()

    for epoch in range(epochs):

        # -------- Forward Pass --------
        hidden_input = np.dot(X, w_input_hidden)
        hidden_output = sigmoid(hidden_input)

        output_input = np.dot(hidden_output, w_hidden_output)
        output = sigmoid(output_input)

        # -------- Loss (MSE) --------
        loss = np.mean((y - output) ** 2)

        # -------- Backpropagation --------
        error_output = y - output
        delta_output = error_output * sigmoid_derivative(output)

        error_hidden = delta_output.dot(w_hidden_output.T)
        delta_hidden = error_hidden * sigmoid_derivative(hidden_output)

        # -------- Gradient Descent --------
        w_hidden_output += hidden_output.T * delta_output * lr
        w_input_hidden += X.T.dot(delta_hidden) * lr

        # REQUIRED OUTPUT FORMAT (every 1000 epochs)
        if epoch % 1000 == 0:
            print(f"Epoch {epoch} - Loss: {loss}")

    print(f"\nFinal Loss for LR {lr}: {loss}")

    # Save best model
    if loss < best_loss:
        best_loss = loss
        best_lr = lr
        best_w_ih = w_input_hidden.copy()
        best_w_ho = w_hidden_output.copy()

# =====================================================
# 6. FINAL DEPLOYED MODEL
# =====================================================
print("\n===== BEST MODEL SELECTED =====")
print("Best Learning Rate:", best_lr)
print("Final Loss:", best_loss)

print("\nFinal Input → Hidden Weights:\n", best_w_ih)
print("\nFinal Hidden → Output Weights:\n", best_w_ho)

# =====================================================
# 7. PREDICTIONS AFTER TRAINING
# =====================================================
print("\nPredictions after training:")

test_inputs = np.array([
    [0.05, 0.10],
    [0.90, 0.95],
    [0.85, 0.80]
])

# Forward pass for prediction
hidden_layer = sigmoid(np.dot(test_inputs, best_w_ih))
predictions = sigmoid(np.dot(hidden_layer, best_w_ho))

print(predictions)